title: Binit Kumar Pandit
logo: /assets/img/mypic.jpeg
description: This is my personal webpage
minimal_mistakes_skin: sunrise # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"
show_downloads: false
google_analytics:
repository: BinitPandit94/binitpandit94.github.io
theme: jekyll-theme-minimal
remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme # add this line to the plugins list if you already have one
  
